kind: pipeline
name: default

# steps:
#   - name: backend
#     image: node:8.15.0-alpine
#     commands:
#       - npm install
#       - npm test
      
steps:
  - name: telegram
    image: appleboy/drone-telegram
    token: 361259032:AAF9jR2H1ZcTGIKjB_HxdI_PIwGAe8nYT1Y
    to: @waldemirflj
    message: >
      {{#success build.status}}
        ✅ build {{build.number}} succeeded. Good job.
      {{else}}
        ❌ build {{build.number}} failed. Fix me please.
      {{/success}}