kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: backend
    image: node:8.15.0-alpine
    commands:
      - npm install
      - npm test

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: waldemir_drone_bot
      token: 702080745:AAFggTF5Is0UzeX4gxBaNIDz77-BKOLrN7c
      when:
        status: [ success, failure ]
      message: >
        {{#success build.status}}
          ✅ build {{build.number}} succeeded. Good job.
        {{else}}
          ❌ build {{build.number}} failed. Fix me please.
        {{/success}}