pipeline:
  npm-install:
    image: node:8.15.0-alpine
    commands:
      - cd api/
      - npm install
    when:
      branch: [ develop ]
      event: [ push ]

  npm-test:
    image: node:8.15.0-alpine
    commands:
      - cd api/
      - npm test
    when:
      branch: [ develop ]
      event: [ push ]
  
  docker-registry-push:
    image: plugins/docker
    repo: waldemirflj/poc-drone
    username: $docker_username
    password: $docker_password
    when:
      branch: [ develop ]
        

