pipeline:
  npm_install:
    image: node:8.15.0-alpine
    commands:
      - npm install
    when:
      branches: develop
      event: push

  npm_test:
    image: node:8.15.0-alpine
    commands:
      - npm test
    when:
      branches: develop
      event: push
