kind: pipeline
name: default

steps:
  - name: backend
    image: node:8.15.0-alpine
    commands:
      - npm install
      - npm test
  - name: telegram
    image: appleboy/drone-telegram
    settings:
      # token: 768557743:AAGO25NAD45-sQAyNPfGQe8B1-TwpQcFzRU
      # to: waldemir_status_bot
      secrets: [ "768557743:AAGO25NAD45-sQAyNPfGQe8B1-TwpQcFzRU", waldemir_status_bot ]
      message: >
        {{#success build.status}}
          ✅ build {{build.number}} succeeded. Good job.
        {{else}}
          ❌ build {{build.number}} failed. Fix me please.
        {{/success}}