pipeline:
  npm_install:
    image: node:8.15.0-alpine
    commands:
      - cd api/
      - npm install
    when:
      branch: [ develop ]
      event: [ push ]

  npm_test:
    image: node:8.15.0-alpine
    commands:
      - cd api/
      - npm test
    when:
      branch: [ develop ]
      event: [ push ]
  
  docker_registry_push:
    image: plugins/docker
    repo: waldemirflj/poc-drone
    username: ${PRIVATE_DOCKER_USERNAME}
    password: ${PRIVATE_DOCKER_PASSWORD}
    when:
      branch: master

