clone:
  depth: true

pipeline:
  npm_install:
    image: node:8.15.0-alpine
    commands:
      - npm install
    when:
      branches: [develop]
      event: [push, pull_request, tag]

  npm_test:
    image: node:8.15.0-alpine
    commands:
      - npm test
    when:
      branches: [develop]
      event: [push, pull_request, tag]
